In [6]:
pip install wrds

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: wrds in /usr/local/lib/python3.9/dist-packages (3.1.6)
Requirement already satisfied: sqlalchemy<2 in /usr/local/lib/python3.9/dist-packages (from wrds) (1.4.47)
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (from wrds) (1.4.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from wrds) (1.22.4)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.9/dist-packages (from wrds) (2.9.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from wrds) (1.10.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.9/dist-packages (from sqlalchemy<2->wrds) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas->wrds) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas->wrds) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas->wrds) (1.16.0)

In [2]:
import wrds
db = wrds.Connection()

Enter your WRDS username [root]:ltee11
Enter your password:··········
WRDS recommends setting up a .pgpass file.
Create .pgpass file now [y/n]?: y
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done

In [9]:
lib = db.list_libraries()
lib
#sorted(lib)

['aha_sample',
 'ahasamp',
 'audit',
 'audit_acct_os',
 'audit_common',
 'audit_corp_legal',
 'audit_europe',
 'auditsmp',
 'auditsmp_all',
 'block',
 'block_all',
 'boardex_trial',
 'boardsmp',
 'bvd',
 'bvd_orbis_large',
 'bvd_orbis_medium',
 'bvd_orbis_small',
 'calcbench_trial',
 'calcbnch',
 'cboe',
 'cboe_all',
 'ciq',
 'ciq_common',
 'ciq_ratings',
 'ciq_transcripts',
 'ciqsamp',
 'ciqsamp_common',
 'ciqsamp_keydev',
 'ciqsamp_transcripts',
 'columnar',
 'comp',
 'comp_bank',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_global',
 'comp_global_daily',
 'comp_na_annual_all',
 'comp_na_daily_all',
 'comp_na_monthly_all',
 'comp_ratings',
 'comp_segments_hist',
 'comp_segments_hist_daily',
 'compa',
 'compb',
 'compg',
 'compm',
 'compsamp_snapshot',
 'compseg',
 'comscore',
 'comscore_2018',
 'comscore_2019',
 'comscore_2020',
 'comscore_common',
 'contrib',
 'contrib_as_filed_financials',
 'contrib_ceo_turnover',
 'contrib_char_returns',
 'contrib_general',
 'contrib_intangible_value',
 'contrib_kpss',
 'contrib_liva',
 'crsp',
 'crsp_a_ccm',
 'crsp_a_indexes',
 'crsp_a_stock',
 'crsp_q_indexes',
 'crsp_q_indexhist',
 'crsp_q_mutualfunds',
 'crspq',
 'csmar',
 'csmar_financial',
 'csmar_funds',
 'csmar_trade',
 'dealscan',
 'djones',
 'djones_all',
 'dmef',
 'dmef_all',
 'doe',
 'doe_all',
 'etfg',
 'etfg_analytics',
 'etfg_constituents',
 'etfg_fund_flow',
 'etfg_industry',
 'etfg_samp',
 'etfgsamp',
 'eurekahedge_sample',
 'eursamp',
 'execcomp',
 'factsamp_all',
 'factsamp_revere',
 'ff',
 'ff_all',
 'fisdsamp',
 'fisdsamp_all',
 'fjc',
 'fjc_linking',
 'fjc_litigation',
 'frb',
 'frb_all',
 'fssamp',
 'ftse',
 'ftse_russell_us',
 'gmi',
 'gmi_all',
 'gutenberg',
 'hbase_sample',
 'hbsamp',
 'hfrsamp',
 'hfrsamp_hfrdb',
 'ibes',
 'ifgrsamp',
 'ims_obp_trial',
 'imssamp',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'iss_va_shareholder',
 'issm_nasd1987',
 'issm_nasd1988',
 'issm_nasd1989',
 'issm_nasd1990',
 'issm_nasd1991',
 'issm_nasd1992',
 'issm_nyam1983',
 'issm_nyam1984',
 'issm_nyam1985',
 'issm_nyam1986',
 'issm_nyam1987',
 'issm_nyam1988',
 'issm_nyam1989',
 'issm_nyam1990',
 'issm_nyam1991',
 'issm_nyam1992',
 'ktmine_patents_samp',
 'ktsamp',
 'lvnsamp',
 'lvnsamp_all',
 'macrofin',
 'macrofin_comm_trade',
 'mfl',
 'mflinks_all',
 'midas',
 'mrktsamp',
 'mrktsamp_cds',
 'mrktsamp_cdx',
 'mrktsamp_msf',
 'msrb',
 'msrb_all',
 'omtrial',
 'optionm',
 'optionm_all',
 'optionmsamp_europe',
 'optionmsamp_us',
 'otc',
 'otc_endofday',
 'phlx',
 'phlx_all',
 'pitchsmp',
 'ppubsamp',
 'ppubsamp_d4d',
 'preqin',
 'preqin_pe',
 'preqin_vc',
 'preqsamp',
 'preqsamp_all',
 'public_all',
 'pwt',
 'pwt_all',
 'ravenpack_trial',
 'reprisk',
 'reprisk_sample',
 'reprisk_v2',
 'repsamp',
 'risk',
 'risk_directors',
 'risk_governance',
 'risk_proposals',
 'risk_votes',
 'risksamp',
 'risksamp_all',
 'rpnasamp',
 'rq_all',
 'secsamp',
 'secsamp_all',
 'snapsamp',
 'snlsamp',
 'snlsamp_fig',
 'sprat',
 'sustain',
 'sustainalytics_all',
 'sustainalyticssamp_all',
 'sustsamp',
 'taqm_2003',
 'taqm_2004',
 'taqm_2005',
 'taqm_2006',
 'taqm_2007',
 'taqm_2008',
 'taqm_2009',
 'taqm_2010',
 'taqm_2011',
 'taqm_2012',
 'taqm_2013',
 'taqm_2014',
 'taqm_2015',
 'taqm_2016',
 'taqm_2017',
 'taqm_2018',
 'taqm_2019',
 'taqm_2020',
 'taqm_2021',
 'taqmsamp',
 'taqmsamp_all',
 'taqmsec',
 'taqsamp',
 'tfn',
 'totalq',
 'totalq_all',
 'tr_13f',
 'tr_common',
 'tr_dealscan',
 'tr_ds_comds',
 'tr_ds_econ',
 'tr_ds_equities',
 'tr_ds_fut',
 'tr_ibes',
 'tr_ibes_guidance',
 'tr_ibes_iga',
 'tr_insiders',
 'tr_mutualfunds',
 'tr_ownership',
 'tr_worldscope',
 'trace',
 'trace_enhanced',
 'trace_standard',
 'trdssamp',
 'trdstrm',
 'trown',
 'trsamp',
 'trsamp_ds_eq',
 'trsamp_dscom',
 'trsamp_dsecon',
 'trsamp_dsfut',
 'trsamp_worldscope',
 'trws',
 'twoiq_samp',
 'twoiqsmp',
 'wappsamp',
 'windsmp',
 'wrds_lib_internal',
 'wrds_sec_search',
 'wrdsapps',
 'wrdsapps_backtest_basic',
 'wrdsapps_backtest_plus',
 'wrdsapps_eushort',
 'wrdsapps_evtstudy_int_ginsight',
 'wrdsapps_evtstudy_lr',
 'wrdsapps_finratio',
 'wrdsapps_finratio_ccm',
 'wrdsapps_finratio_ibes',
 'wrdsapps_finratio_ibes_ccm',
 'wrdsapps_link_comp_eushort',
 'wrdsapps_link_crsp_bond',
 'wrdsapps_link_crsp_factset',
 'wrdsapps_link_crsp_ibes',
 'wrdsapps_link_crsp_optionm',
 'wrdsapps_link_crsp_taq',
 'wrdsapps_link_datastream_wscope',
 'wrdsapps_link_supplychain',
 'wrdsapps_patents',
 'wrdsapps_plink_exec_trinsider',
 'wrdsapps_subsidiary',
 'wrdsapps_windices',
 'wrdsappssamp_all',
 'wrdssec',
 'wrdssec_all',
 'wrdssec_bow',
 'wrdssec_common',
 'wrdssec_insiders',
 'wrdssec_midas',
 'wrdssec_secsa',
 'zacksamp',
 'zacksamp_all']

In [9]:
lib = db.list_libraries()
comp = [x for x in lib if 'comp' in x]
comp

#comp = list(filter(lambda x: 'comp' in x, lib))
#comp

#import re
#comp = [x for x in lib if re.search('comp', x)]
#comp

['comp',
 'comp_bank',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_global',
 'comp_global_daily',
 'comp_na_annual_all',
 'comp_na_daily_all',
 'comp_na_monthly_all',
 'comp_ratings',
 'comp_segments_hist',
 'comp_segments_hist_daily',
 'compa',
 'compb',
 'compg',
 'compm',
 'compsamp_snapshot',
 'compseg',
 'execcomp',
 'wrdsapps_link_comp_eushort']

In [10]:
tables = db.list_tables(library='comp_na_daily_all')
tables

['aco_amda',
 'aco_imda',
 'aco_indfnta',
 'aco_indfntq',
 'aco_indfntytd',
 'aco_indsta',
 'aco_indstq',
 'aco_indstytd',
 'aco_notesa',
 'aco_notesq',
 'aco_notessa',
 'aco_notesytd',
 'aco_pnfnda',
 'aco_pnfndq',
 'aco_pnfndytd',
 'aco_pnfnta',
 'aco_pnfntq',
 'aco_pnfntytd',
 'aco_transa',
 'aco_transq',
 'aco_transsa',
 'aco_transytd',
 'adsprate',
 'asec_amda',
 'asec_imda',
 'asec_notesa',
 'asec_notesq',
 'asec_transa',
 'asec_transq',
 'chars',
 'co_aacctchg',
 'co_aaudit',
 'co_adesind',
 'co_adjfact',
 'co_afnd1',
 'co_afnd2',
 'co_afnddc1',
 'co_afnddc2',
 'co_afntind1',
 'co_afntind2',
 'co_ainvval',
 'co_amkt',
 'co_busdescl',
 'co_cotype',
 'co_filedate',
 'co_fortune',
 'co_hgic',
 'co_iacctchg',
 'co_iaudit',
 'co_idesind',
 'co_ifndq',
 'co_ifndsa',
 'co_ifndytd',
 'co_ifntq',
 'co_ifntsa',
 'co_ifntytd',
 'co_imkt',
 'co_industry',
 'co_ipcd',
 'co_mthly',
 'co_offtitl',
 'company',
 'currency',
 'dd_group',
 'dd_group_xref',
 'dd_item',
 'dd_package',
 'ecind_desc',
 'ecind_mth',
 'exrt_dly',
 'exrt_mth',
 'funda',
 'funda_fncd',
 'fundq',
 'fundq_fncd',
 'idx_ann',
 'idx_anndes',
 'idx_daily',
 'idx_index',
 'idx_mth',
 'idx_qrt',
 'idx_qrtdes',
 'idxcst_his',
 'io_qaggregate',
 'io_qbuysell',
 'io_qchanges',
 'io_qfloatadj',
 'io_qholders',
 'it_mbuysell',
 'it_msummary',
 'it_r_rltn',
 'names',
 'names_aco_indsta',
 'names_aco_indstq',
 'names_aco_pnfnda',
 'names_aco_pnfndq',
 'names_adsprate',
 'names_ix',
 'names_ix_cst',
 'names_seg',
 'namesd',
 'namesm',
 'namesq',
 'r_accstd',
 'r_acqmeth',
 'r_auditors',
 'r_auopic',
 'r_balpres',
 'r_cf_formt',
 'r_co_status',
 'r_coindpre',
 'r_compstat',
 'r_consol',
 'r_country',
 'r_cstclscd',
 'r_datacode',
 'r_datafmt',
 'r_divtaxmarker',
 'r_docsrce',
 'r_ex_codes',
 'r_exchgtier',
 'r_exrt_typ',
 'r_fndfntcd',
 'r_footnts',
 'r_foricd',
 'r_giccd',
 'r_hcalendr',
 'r_idxclscd',
 'r_inactvcd',
 'r_incstats',
 'r_indfmt',
 'r_indsec',
 'r_invval',
 'r_issuetyp',
 'r_majidxcl',
 'r_mic_codes',
 'r_naiccd',
 'r_notetype',
 'r_ntsubtype',
 'r_offcrso',
 'r_ogmethod',
 'r_opinions',
 'r_prc_stat',
 'r_qsrcdoc',
 'r_sec_stat',
 'r_secannfn',
 'r_sectors',
 'r_siccd',
 'r_spiicd',
 'r_spmicd',
 'r_statalrt',
 'r_states',
 'r_stko',
 'r_titles',
 'r_updates',
 'sec_adesind',
 'sec_adjfact',
 'sec_afnd',
 'sec_afnddc',
 'sec_afnt',
 'sec_divid',
 'sec_dprc',
 'sec_dtrt',
 'sec_history',
 'sec_idesind',
 'sec_ifnd',
 'sec_ifnt',
 'sec_mdivfn',
 'sec_mshare',
 'sec_msptfn',
 'sec_mth',
 'sec_mthdiv',
 'sec_mthprc',
 'sec_mthspt',
 'sec_mthtrt',
 'sec_shortint',
 'sec_spind',
 'sec_split',
 'secd',
 'secm',
 'security',
 'sedolgvkey',
 'seg_ann',
 'seg_annfund',
 'seg_customer',
 'seg_geo',
 'seg_naics',
 'seg_product',
 'seg_type',
 'spidx_cst',
 'spind',
 'spind_dly',
 'spind_mth',
 'wrds_seg_customer',
 'wrds_seg_geo',
 'wrds_seg_product',
 'wrds_segmerged',
 'xfl_column',
 'xfl_table']

In [12]:
tables = db.list_tables(library='comp_na_daily_all')
tables 

#open file in write mode
with open(r'tables_OF_comp_na_daily_all.txt', 'w') as a:
    
    for b in tables:
        #write each item on a new line
        a.write("%s\n" % b)
    print()

In [13]:
column_headers = db.describe_table(library='comp_na_daily_all', table='fundq')
print(column_headers.to_string())

Approximately 1952140 rows in comp_na_daily_all.fundq.
           name  nullable              type comment
0         gvkey      True        VARCHAR(6)    None
1      datadate      True              DATE    None
2        fyearq      True  DOUBLE_PRECISION    None
3          fqtr      True  DOUBLE_PRECISION    None
4           fyr      True  DOUBLE_PRECISION    None
5        indfmt      True       VARCHAR(12)    None
6        consol      True        VARCHAR(2)    None
7        popsrc      True        VARCHAR(1)    None
8       datafmt      True       VARCHAR(12)    None
9           tic      True        VARCHAR(8)    None
10        cusip      True        VARCHAR(9)    None
11         conm      True       VARCHAR(70)    None
12     acctchgq      True        VARCHAR(8)    None
13     acctstdq      True        VARCHAR(8)    None
14        adrrq      True  DOUBLE_PRECISION    None
15        ajexq      True  DOUBLE_PRECISION    None
16         ajpq      True  DOUBLE_PRECISION    None
17        bsprq      True        VARCHAR(8)    None
18      compstq      True        VARCHAR(8)    None
19       curcdq      True        VARCHAR(3)    None
20      curncdq      True        VARCHAR(3)    None
21      currtrq      True  DOUBLE_PRECISION    None
22     curuscnq      True  DOUBLE_PRECISION    None
23     datacqtr      True        VARCHAR(6)    None
24     datafqtr      True        VARCHAR(6)    None
25       finalq      True        VARCHAR(2)    None
26         ogmq      True        VARCHAR(8)    None
27           rp      True        VARCHAR(2)    None
28         scfq      True  DOUBLE_PRECISION    None
29         srcq      True  DOUBLE_PRECISION    None
30       staltq      True        VARCHAR(2)    None
31         updq      True  DOUBLE_PRECISION    None
32    apdedateq      True              DATE    None
33       fdateq      True              DATE    None
34       pdateq      True              DATE    None
35          rdq      True              DATE    None
36       acchgq      True  DOUBLE_PRECISION    None
37     acomincq      True  DOUBLE_PRECISION    None
38         acoq      True  DOUBLE_PRECISION    None
39         actq      True  DOUBLE_PRECISION    None
40        altoq      True  DOUBLE_PRECISION    None
41         ancq      True  DOUBLE_PRECISION    None
42         anoq      True  DOUBLE_PRECISION    None
43   aociderglq      True  DOUBLE_PRECISION    None
44   aociotherq      True  DOUBLE_PRECISION    None
45     aocipenq      True  DOUBLE_PRECISION    None
46   aocisecglq      True  DOUBLE_PRECISION    None
47        aol2q      True  DOUBLE_PRECISION    None
48          aoq      True  DOUBLE_PRECISION    None
49          apq      True  DOUBLE_PRECISION    None
50         aqaq      True  DOUBLE_PRECISION    None
51         aqdq      True  DOUBLE_PRECISION    None
52       aqepsq      True  DOUBLE_PRECISION    None
53       aqpl1q      True  DOUBLE_PRECISION    None
54         aqpq      True  DOUBLE_PRECISION    None
55       arcedq      True  DOUBLE_PRECISION    None
56     arceepsq      True  DOUBLE_PRECISION    None
57        arceq      True  DOUBLE_PRECISION    None
58          atq      True  DOUBLE_PRECISION    None
59        aul3q      True  DOUBLE_PRECISION    None
60    billexceq      True  DOUBLE_PRECISION    None
61       capr1q      True  DOUBLE_PRECISION    None
62       capr2q      True  DOUBLE_PRECISION    None
63       capr3q      True  DOUBLE_PRECISION    None
64      capsftq      True  DOUBLE_PRECISION    None
65        capsq      True  DOUBLE_PRECISION    None
66   ceiexbillq      True  DOUBLE_PRECISION    None
67         ceqq      True  DOUBLE_PRECISION    None
68         cheq      True  DOUBLE_PRECISION    None
69          chq      True  DOUBLE_PRECISION    None
70     cibegniq      True  DOUBLE_PRECISION    None
71      cicurrq      True  DOUBLE_PRECISION    None
72     ciderglq      True  DOUBLE_PRECISION    None
73       cimiiq      True  DOUBLE_PRECISION    None
74     ciotherq      True  DOUBLE_PRECISION    None
75       cipenq      True  DOUBLE_PRECISION    None
76          ciq      True  DOUBLE_PRECISION    None
77     cisecglq      True  DOUBLE_PRECISION    None
78     citotalq      True  DOUBLE_PRECISION    None
79        cogsq      True  DOUBLE_PRECISION    None
80       csh12q      True  DOUBLE_PRECISION    None
81      cshfd12      True  DOUBLE_PRECISION    None
82       cshfdq      True  DOUBLE_PRECISION    None
83        cshiq      True  DOUBLE_PRECISION    None
84       cshopq      True  DOUBLE_PRECISION    None
85        cshoq      True  DOUBLE_PRECISION    None
86       cshprq      True  DOUBLE_PRECISION    None
87      cstkcvq      True  DOUBLE_PRECISION    None
88       cstkeq      True  DOUBLE_PRECISION    None
89        cstkq      True  DOUBLE_PRECISION    None
90        dcomq      True  DOUBLE_PRECISION    None
91         dd1q      True  DOUBLE_PRECISION    None
92       deracq      True  DOUBLE_PRECISION    None
93      deraltq      True  DOUBLE_PRECISION    None
94    derhedglq      True  DOUBLE_PRECISION    None
95       derlcq      True  DOUBLE_PRECISION    None
96      derlltq      True  DOUBLE_PRECISION    None
97       diladq      True  DOUBLE_PRECISION    None
98       dilavq      True  DOUBLE_PRECISION    None
99         dlcq      True  DOUBLE_PRECISION    None
100       dlttq      True  DOUBLE_PRECISION    None
101         doq      True  DOUBLE_PRECISION    None
102     dpacreq      True  DOUBLE_PRECISION    None
103      dpactq      True  DOUBLE_PRECISION    None
104         dpq      True  DOUBLE_PRECISION    None
105      dpretq      True  DOUBLE_PRECISION    None
106        drcq      True  DOUBLE_PRECISION    None
107       drltq      True  DOUBLE_PRECISION    None
108       dteaq      True  DOUBLE_PRECISION    None
109       dtedq      True  DOUBLE_PRECISION    None
110     dteepsq      True  DOUBLE_PRECISION    None
111       dtepq      True  DOUBLE_PRECISION    None
112     dvintfq      True  DOUBLE_PRECISION    None
113        dvpq      True  DOUBLE_PRECISION    None
114      epsf12      True  DOUBLE_PRECISION    None
115     epsfi12      True  DOUBLE_PRECISION    None
116      epsfiq      True  DOUBLE_PRECISION    None
117      epsfxq      True  DOUBLE_PRECISION    None
118     epspi12      True  DOUBLE_PRECISION    None
119      epspiq      True  DOUBLE_PRECISION    None
120      epspxq      True  DOUBLE_PRECISION    None
121      epsx12      True  DOUBLE_PRECISION    None
122     esopctq      True  DOUBLE_PRECISION    None
123     esopnrq      True  DOUBLE_PRECISION    None
124      esoprq      True  DOUBLE_PRECISION    None
125      esoptq      True  DOUBLE_PRECISION    None
126       esubq      True  DOUBLE_PRECISION    None
127        fcaq      True  DOUBLE_PRECISION    None
128        ffoq      True  DOUBLE_PRECISION    None
129     finacoq      True  DOUBLE_PRECISION    None
130      finaoq      True  DOUBLE_PRECISION    None
131      finchq      True  DOUBLE_PRECISION    None
132     findlcq      True  DOUBLE_PRECISION    None
133     findltq      True  DOUBLE_PRECISION    None
134    finivstq      True  DOUBLE_PRECISION    None
135     finlcoq      True  DOUBLE_PRECISION    None
136     finltoq      True  DOUBLE_PRECISION    None
137      finnpq      True  DOUBLE_PRECISION    None
138    finreccq      True  DOUBLE_PRECISION    None
139   finrecltq      True  DOUBLE_PRECISION    None
140     finrevq      True  DOUBLE_PRECISION    None
141    finxintq      True  DOUBLE_PRECISION    None
142    finxoprq      True  DOUBLE_PRECISION    None
143     gdwlamq      True  DOUBLE_PRECISION    None
144    gdwlia12      True  DOUBLE_PRECISION    None
145     gdwliaq      True  DOUBLE_PRECISION    None
146    gdwlid12      True  DOUBLE_PRECISION    None
147     gdwlidq      True  DOUBLE_PRECISION    None
148  gdwlieps12      True  DOUBLE_PRECISION    None
149   gdwliepsq      True  DOUBLE_PRECISION    None
150     gdwlipq      True  DOUBLE_PRECISION    None
151       gdwlq      True  DOUBLE_PRECISION    None
152        glaq      True  DOUBLE_PRECISION    None
153     glcea12      True  DOUBLE_PRECISION    None
154      glceaq      True  DOUBLE_PRECISION    None
155     glced12      True  DOUBLE_PRECISION    None
156      glcedq      True  DOUBLE_PRECISION    None
157   glceeps12      True  DOUBLE_PRECISION    None
158    glceepsq      True  DOUBLE_PRECISION    None
159      glcepq      True  DOUBLE_PRECISION    None
160        gldq      True  DOUBLE_PRECISION    None
161      glepsq      True  DOUBLE_PRECISION    None
162       glivq      True  DOUBLE_PRECISION    None
163        glpq      True  DOUBLE_PRECISION    None
164    hedgeglq      True  DOUBLE_PRECISION    None
165     ibadj12      True  DOUBLE_PRECISION    None
166      ibadjq      True  DOUBLE_PRECISION    None
167      ibcomq      True  DOUBLE_PRECISION    None
168      ibmiiq      True  DOUBLE_PRECISION    None
169         ibq      True  DOUBLE_PRECISION    None
170      icaptq      True  DOUBLE_PRECISION    None
171     intaccq      True  DOUBLE_PRECISION    None
172     intanoq      True  DOUBLE_PRECISION    None
173      intanq      True  DOUBLE_PRECISION    None
174      invfgq      True  DOUBLE_PRECISION    None
175       invoq      True  DOUBLE_PRECISION    None
176      invrmq      True  DOUBLE_PRECISION    None
177       invtq      True  DOUBLE_PRECISION    None
178     invwipq      True  DOUBLE_PRECISION    None
179      ivaeqq      True  DOUBLE_PRECISION    None
180       ivaoq      True  DOUBLE_PRECISION    None
181       ivltq      True  DOUBLE_PRECISION    None
182       ivstq      True  DOUBLE_PRECISION    None
183        lcoq      True  DOUBLE_PRECISION    None
184        lctq      True  DOUBLE_PRECISION    None
185        lltq      True  DOUBLE_PRECISION    None
186        lnoq      True  DOUBLE_PRECISION    None
187       lol2q      True  DOUBLE_PRECISION    None
188         loq      True  DOUBLE_PRECISION    None
189      loxdrq      True  DOUBLE_PRECISION    None
190      lqpl1q      True  DOUBLE_PRECISION    None
191        lseq      True  DOUBLE_PRECISION    None
192      ltmibq      True  DOUBLE_PRECISION    None
193         ltq      True  DOUBLE_PRECISION    None
194       lul3q      True  DOUBLE_PRECISION    None
195       mibnq      True  DOUBLE_PRECISION    None
196        mibq      True  DOUBLE_PRECISION    None
197       mibtq      True  DOUBLE_PRECISION    None
198        miiq      True  DOUBLE_PRECISION    None
199        msaq      True  DOUBLE_PRECISION    None
200        ncoq      True  DOUBLE_PRECISION    None
201       niitq      True  DOUBLE_PRECISION    None
202        nimq      True  DOUBLE_PRECISION    None
203         niq      True  DOUBLE_PRECISION    None
204       nopiq      True  DOUBLE_PRECISION    None
205       npatq      True  DOUBLE_PRECISION    None
206         npq      True  DOUBLE_PRECISION    None
207     nrtxtdq      True  DOUBLE_PRECISION    None
208   nrtxtepsq      True  DOUBLE_PRECISION    None
209      nrtxtq      True  DOUBLE_PRECISION    None
210        obkq      True  DOUBLE_PRECISION    None
211      oepf12      True  DOUBLE_PRECISION    None
212      oeps12      True  DOUBLE_PRECISION    None
213      oepsxq      True  DOUBLE_PRECISION    None
214      oiadpq      True  DOUBLE_PRECISION    None
215      oibdpq      True  DOUBLE_PRECISION    None
216      opepsq      True  DOUBLE_PRECISION    None
217      optdrq      True  DOUBLE_PRECISION    None
218    optfvgrq      True  DOUBLE_PRECISION    None
219    optlifeq      True  DOUBLE_PRECISION    None
220     optrfrq      True  DOUBLE_PRECISION    None
221     optvolq      True  DOUBLE_PRECISION    None
222         piq      True  DOUBLE_PRECISION    None
223        pllq      True  DOUBLE_PRECISION    None
224       pnc12      True  DOUBLE_PRECISION    None
225      pncd12      True  DOUBLE_PRECISION    None
226       pncdq      True  DOUBLE_PRECISION    None
227    pnceps12      True  DOUBLE_PRECISION    None
228     pncepsq      True  DOUBLE_PRECISION    None
229     pnciapq      True  DOUBLE_PRECISION    None
230      pnciaq      True  DOUBLE_PRECISION    None
231     pncidpq      True  DOUBLE_PRECISION    None
232      pncidq      True  DOUBLE_PRECISION    None
233   pnciepspq      True  DOUBLE_PRECISION    None
234    pnciepsq      True  DOUBLE_PRECISION    None
235     pncippq      True  DOUBLE_PRECISION    None
236      pncipq      True  DOUBLE_PRECISION    None
237     pncpd12      True  DOUBLE_PRECISION    None
238      pncpdq      True  DOUBLE_PRECISION    None
239   pncpeps12      True  DOUBLE_PRECISION    None
240    pncpepsq      True  DOUBLE_PRECISION    None
241       pncpq      True  DOUBLE_PRECISION    None
242        pncq      True  DOUBLE_PRECISION    None
243    pncwiapq      True  DOUBLE_PRECISION    None
244     pncwiaq      True  DOUBLE_PRECISION    None
245    pncwidpq      True  DOUBLE_PRECISION    None
246     pncwidq      True  DOUBLE_PRECISION    None
247    pncwiepq      True  DOUBLE_PRECISION    None
248   pncwiepsq      True  DOUBLE_PRECISION    None
249    pncwippq      True  DOUBLE_PRECISION    None
250     pncwipq      True  DOUBLE_PRECISION    None
251     pnrshoq      True  DOUBLE_PRECISION    None
252      ppegtq      True  DOUBLE_PRECISION    None
253      ppentq      True  DOUBLE_PRECISION    None
254       prcaq      True  DOUBLE_PRECISION    None
255      prcd12      True  DOUBLE_PRECISION    None
256       prcdq      True  DOUBLE_PRECISION    None
257      prce12      True  DOUBLE_PRECISION    None
258    prceps12      True  DOUBLE_PRECISION    None
259     prcepsq      True  DOUBLE_PRECISION    None
260     prcpd12      True  DOUBLE_PRECISION    None
261      prcpdq      True  DOUBLE_PRECISION    None
262   prcpeps12      True  DOUBLE_PRECISION    None
263    prcpepsq      True  DOUBLE_PRECISION    None
264       prcpq      True  DOUBLE_PRECISION    None
265      prcraq      True  DOUBLE_PRECISION    None
266      prshoq      True  DOUBLE_PRECISION    None
267      pstknq      True  DOUBLE_PRECISION    None
268       pstkq      True  DOUBLE_PRECISION    None
269      pstkrq      True  DOUBLE_PRECISION    None
270        rcaq      True  DOUBLE_PRECISION    None
271        rcdq      True  DOUBLE_PRECISION    None
272      rcepsq      True  DOUBLE_PRECISION    None
273        rcpq      True  DOUBLE_PRECISION    None
274      rdipaq      True  DOUBLE_PRECISION    None
275      rdipdq      True  DOUBLE_PRECISION    None
276    rdipepsq      True  DOUBLE_PRECISION    None
277       rdipq      True  DOUBLE_PRECISION    None
278       recdq      True  DOUBLE_PRECISION    None
279      rectaq      True  DOUBLE_PRECISION    None
280      rectoq      True  DOUBLE_PRECISION    None
281       rectq      True  DOUBLE_PRECISION    None
282      rectrq      True  DOUBLE_PRECISION    None
283      recubq      True  DOUBLE_PRECISION    None
284         req      True  DOUBLE_PRECISION    None
285        retq      True  DOUBLE_PRECISION    None
286      reunaq      True  DOUBLE_PRECISION    None
287       revtq      True  DOUBLE_PRECISION    None
288        rllq      True  DOUBLE_PRECISION    None
289       rra12      True  DOUBLE_PRECISION    None
290        rraq      True  DOUBLE_PRECISION    None
291       rrd12      True  DOUBLE_PRECISION    None
292        rrdq      True  DOUBLE_PRECISION    None
293     rreps12      True  DOUBLE_PRECISION    None
294      rrepsq      True  DOUBLE_PRECISION    None
295        rrpq      True  DOUBLE_PRECISION    None
296   rstcheltq      True  DOUBLE_PRECISION    None
297     rstcheq      True  DOUBLE_PRECISION    None
298       saleq      True  DOUBLE_PRECISION    None
299       seqoq      True  DOUBLE_PRECISION    None
300        seqq      True  DOUBLE_PRECISION    None
301      seta12      True  DOUBLE_PRECISION    None
302       setaq      True  DOUBLE_PRECISION    None
303      setd12      True  DOUBLE_PRECISION    None
304       setdq      True  DOUBLE_PRECISION    None
305    seteps12      True  DOUBLE_PRECISION    None
306     setepsq      True  DOUBLE_PRECISION    None
307       setpq      True  DOUBLE_PRECISION    None
308      spce12      True  DOUBLE_PRECISION    None
309     spced12      True  DOUBLE_PRECISION    None
310     spcedpq      True  DOUBLE_PRECISION    None
311      spcedq      True  DOUBLE_PRECISION    None
312   spceeps12      True  DOUBLE_PRECISION    None
313  spceepsp12      True  DOUBLE_PRECISION    None
314   spceepspq      True  DOUBLE_PRECISION    None
315    spceepsq      True  DOUBLE_PRECISION    None
316     spcep12      True  DOUBLE_PRECISION    None
317    spcepd12      True  DOUBLE_PRECISION    None
318      spcepq      True  DOUBLE_PRECISION    None
319       spceq      True  DOUBLE_PRECISION    None
320       spidq      True  DOUBLE_PRECISION    None
321     spiepsq      True  DOUBLE_PRECISION    None
322      spioaq      True  DOUBLE_PRECISION    None
323      spiopq      True  DOUBLE_PRECISION    None
324        spiq      True  DOUBLE_PRECISION    None
325       sretq      True  DOUBLE_PRECISION    None
326      stkcoq      True  DOUBLE_PRECISION    None
327     stkcpaq      True  DOUBLE_PRECISION    None
328        teqq      True  DOUBLE_PRECISION    None
329       tfvaq      True  DOUBLE_PRECISION    None
330      tfvceq      True  DOUBLE_PRECISION    None
331       tfvlq      True  DOUBLE_PRECISION    None
332        tieq      True  DOUBLE_PRECISION    None
333        tiiq      True  DOUBLE_PRECISION    None
334      tstknq      True  DOUBLE_PRECISION    None
335       tstkq      True  DOUBLE_PRECISION    None
336      txdbaq      True  DOUBLE_PRECISION    None
337     txdbcaq      True  DOUBLE_PRECISION    None
338     txdbclq      True  DOUBLE_PRECISION    None
339       txdbq      True  DOUBLE_PRECISION    None
340       txdiq      True  DOUBLE_PRECISION    None
341     txditcq      True  DOUBLE_PRECISION    None
342        txpq      True  DOUBLE_PRECISION    None
343        txtq      True  DOUBLE_PRECISION    None
344        txwq      True  DOUBLE_PRECISION    None
345       uacoq      True  DOUBLE_PRECISION    None
346        uaoq      True  DOUBLE_PRECISION    None
347       uaptq      True  DOUBLE_PRECISION    None
348      ucapsq      True  DOUBLE_PRECISION    None
349     ucconsq      True  DOUBLE_PRECISION    None
350       uceqq      True  DOUBLE_PRECISION    None
351        uddq      True  DOUBLE_PRECISION    None
352       udmbq      True  DOUBLE_PRECISION    None
353      udoltq      True  DOUBLE_PRECISION    None
354      udpcoq      True  DOUBLE_PRECISION    None
355       udvpq      True  DOUBLE_PRECISION    None
356        ugiq      True  DOUBLE_PRECISION    None
357       uinvq      True  DOUBLE_PRECISION    None
358       ulcoq      True  DOUBLE_PRECISION    None
359     uniamiq      True  DOUBLE_PRECISION    None
360    unopincq      True  DOUBLE_PRECISION    None
361       uopiq      True  DOUBLE_PRECISION    None
362      updvpq      True  DOUBLE_PRECISION    None
363    upmcstkq      True  DOUBLE_PRECISION    None
364      upmpfq      True  DOUBLE_PRECISION    None
365     upmpfsq      True  DOUBLE_PRECISION    None
366    upmsubpq      True  DOUBLE_PRECISION    None
367     upstkcq      True  DOUBLE_PRECISION    None
368      upstkq      True  DOUBLE_PRECISION    None
369      urectq      True  DOUBLE_PRECISION    None
370       uspiq      True  DOUBLE_PRECISION    None
371    usubdvpq      True  DOUBLE_PRECISION    None
372    usubpcvq      True  DOUBLE_PRECISION    None
373       utemq      True  DOUBLE_PRECISION    None
374       wcapq      True  DOUBLE_PRECISION    None
375        wdaq      True  DOUBLE_PRECISION    None
376        wddq      True  DOUBLE_PRECISION    None
377      wdepsq      True  DOUBLE_PRECISION    None
378        wdpq      True  DOUBLE_PRECISION    None
379       xaccq      True  DOUBLE_PRECISION    None
380       xidoq      True  DOUBLE_PRECISION    None
381       xintq      True  DOUBLE_PRECISION    None

In [14]:
db.describe_table(library='crsp_a_stock', table='msf')

Approximately 4901600 rows in crsp_a_stock.msf.

,name,nullable,type,comment
0,cusip,True,VARCHAR(8),CUSIP Header
1,permno,True,DOUBLE_PRECISION,PERMNO
2,permco,True,DOUBLE_PRECISION,PERMCO
3,issuno,True,DOUBLE_PRECISION,Nasdaq Issue Number
4,hexcd,True,DOUBLE_PRECISION,Exchange Code Header
5,hsiccd,True,DOUBLE_PRECISION,Standard Industrial Classification Code
6,date,True,DATE,Date of Observation
7,bidlo,True,DOUBLE_PRECISION,Bid or Low Price
8,askhi,True,DOUBLE_PRECISION,Ask or High Price
9,prc,True,DOUBLE_PRECISION,Price or Bid/Ask Average
10,vol,True,DOUBLE_PRECISION,Volume
11,ret,True,DOUBLE_PRECISION,Returns
12,bid,True,DOUBLE_PRECISION,Bid
13,ask,True,DOUBLE_PRECISION,Ask
14,shrout,True,DOUBLE_PRECISION,Shares Outstanding
15,cfacpr,True,DOUBLE_PRECISION,Cumulative Factor to Adjust Prices
16,cfacshr,True,DOUBLE_PRECISION,Cumulative Factor to Adjust Shares/Vol
17,altprc,True,DOUBLE_PRECISION,Price Alternate
18,spread,True,DOUBLE_PRECISION,Spread Between Bid and Ask
19,altprcdt,True,DATE,Alternate Price Date
20,retx,True,DOUBLE_PRECISION,Returns without Dividends

In [15]:
db.get_row_count(library='comp_na_daily_all', table='fundq')
#db.get_row_count('comp_na_daily_all', 'fundq')

1952140

In [ ]:
#import wrds

#db = wrds.Connection()

#db.list_libraries()

#db.list_tables(library='comp_na_daily_all')
#db.list_tables('comp_na_daily_all')

#db.describe_table(library='comp_na_daily_all', table='fundq')
#db.describe_table('comp_na_daily_all','fundq')

#db.get_row_count(library='comp_na_daily_all', table='fundq')
#db.get_row_count('comp_na_daily_all', 'fundq')

In [16]:
db.get_table(library='comp_na_daily_all', table='fundq', obs=10)
#db.get_table(library='comp_na_daily_all', table='fundq')

,gvkey,datadate,fyearq,fqtr,fyr,indfmt,consol,popsrc,datafmt,tic,...,costat,fic,cshtrq,dvpspq,dvpsxq,mkvaltq,prccq,prchq,prclq,adjex
0,001000,1966-03-31,1966.0,1.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
1,001000,1966-06-30,1966.0,2.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
2,001000,1966-09-30,1966.0,3.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
3,001000,1966-12-31,1966.0,4.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
4,001000,1967-03-31,1967.0,1.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
5,001000,1967-06-30,1967.0,2.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
6,001000,1967-09-30,1967.0,3.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
7,001000,1967-12-31,1967.0,4.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
8,001000,1968-03-31,1968.0,1.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999
9,001000,1968-06-30,1968.0,2.0,12.0,INDL,C,D,STD,AE.2,...,I,USA,None,None,0.0,None,None,None,None,3.089999

In [3]:
amazon_ibm = db.raw_sql("""select datadate, gvkey, conm, tic, cusip, atq, ltq, niq, teqq
                        from comp_na_daily_all.fundq
                        where (tic = 'IBM' or tic = 'AMZN')
                        and datadate>='01/01/2010' and datadate<='12/31/2020'""",
                        date_cols=['datadate'])
amazon_ibm

,datadate,gvkey,conm,tic,cusip,atq,ltq,niq,teqq
0,2016-09-30,006066,INTL BUSINESS MACHINES CORP,IBM,459200101,115606.0,98447.0,2853.0,17159.0
1,2010-03-31,006066,INTL BUSINESS MACHINES CORP,IBM,459200101,105208.0,83059.0,2601.0,22149.0
2,2010-06-30,006066,INTL BUSINESS MACHINES CORP,IBM,459200101,103420.0,82244.0,3386.0,21176.0
3,2010-09-30,006066,INTL BUSINESS MACHINES CORP,IBM,459200101,107174.0,84815.0,3589.0,22359.0
4,2010-12-31,006066,INTL BUSINESS MACHINES CORP,IBM,459200101,113452.0,90280.0,5257.0,23172.0
...,...,...,...,...,...,...,...,...,...
83,2019-12-31,064768,AMAZON.COM INC,AMZN,023135106,225248.0,163188.0,3268.0,62060.0
84,2020-03-31,064768,AMAZON.COM INC,AMZN,023135106,221238.0,155966.0,2535.0,65272.0
85,2020-06-30,064768,AMAZON.COM INC,AMZN,023135106,258314.0,184586.0,5243.0,73728.0
86,2020-09-30,064768,AMAZON.COM INC,AMZN,023135106,282179.0,199404.0,6331.0,82775.0
87,2020-12-31,064768,AMAZON.COM INC,AMZN,023135106,321195.0,227791.0,7222.0,93404.0

In [ ]:
amazon_ibm.to_csv('amazon_ibm.csv')

In [7]:
apple = db.raw_sql("""select permno, date, prc, ret, shrout 
                      from crsp_a_stock.msf 
                      where permno = 14593
                      and date>='01/01/2021'
                      and date<='12/31/2021'""", 
                      date_cols=['date'])
apple

     permno       date         prc       ret      shrout
0   14593.0 2021-01-29  131.960007 -0.005502  16788096.0
1   14593.0 2021-02-26  121.260002 -0.079532  16788096.0
2   14593.0 2021-03-31  122.150002  0.007340  16686305.0
3   14593.0 2021-04-30  131.460007  0.076218  16687631.0
4   14593.0 2021-05-28  124.610001 -0.050434  16687631.0
5   14593.0 2021-06-30  136.960007  0.099109  16556942.0
6   14593.0 2021-07-30  145.860001  0.064982  16530166.0
7   14593.0 2021-08-31  151.830002  0.042438  16530166.0
8   14593.0 2021-09-30  141.500000 -0.068037  16426786.0
9   14593.0 2021-10-29  149.800003  0.058657  16406397.0
10  14593.0 2021-11-30  165.300003  0.104940  16406397.0
11  14593.0 2021-12-31  177.570007  0.074229  16344923.0

In [8]:
apple.to_csv('apple.csv')

In [9]:
import pandas as pd
df = pd.read_csv('apple.csv')
print(df.to_string())

    Unnamed: 0   permno        date         prc       ret      shrout
0            0  14593.0  2021-01-29  131.960007 -0.005502  16788096.0
1            1  14593.0  2021-02-26  121.260002 -0.079532  16788096.0
2            2  14593.0  2021-03-31  122.150002  0.007340  16686305.0
3            3  14593.0  2021-04-30  131.460007  0.076218  16687631.0
4            4  14593.0  2021-05-28  124.610001 -0.050434  16687631.0
5            5  14593.0  2021-06-30  136.960007  0.099109  16556942.0
6            6  14593.0  2021-07-30  145.860001  0.064982  16530166.0
7            7  14593.0  2021-08-31  151.830002  0.042438  16530166.0
8            8  14593.0  2021-09-30  141.500000 -0.068037  16426786.0
9            9  14593.0  2021-10-29  149.800003  0.058657  16406397.0
10          10  14593.0  2021-11-30  165.300003  0.104940  16406397.0
11          11  14593.0  2021-12-31  177.570007  0.074229  16344923.0

In [ ]:
apple = db.raw_sql("""select count (*)
                      from crsp_a_stock.msf 
                      """)
apple

Loading library list...
Done

     count
0  4834507

In [4]:
mfs = db.raw_sql("""select fund_name, ticker, first_offer_dt, mgmt_fee
                    from crsp_q_mutualfunds.fund_summary2 
                    limit 03""")
mfs

                        fund_name ticker first_offer_dt  mgmt_fee
0  AARP Income Tr:Bond for Income  AABIX     1997-02-01    -0.282
1  AARP Income Tr:Bond for Income  AABIX     1997-02-01     0.084
2  AARP Income Tr:Bond for Income  AABIX     1997-02-01     0.084

In [5]:
db.get_table(library='crsp_q_mutualfunds', table='fund_summary2', columns = ['fund_name', 'ticker', 'first_offer_dt', 'mgmt_fee'], obs=3)

                        fund_name ticker first_offer_dt  mgmt_fee
0  AARP Income Tr:Bond for Income  AABIX     1997-02-01    -0.282
1  AARP Income Tr:Bond for Income  AABIX     1997-02-01     0.084
2  AARP Income Tr:Bond for Income  AABIX     1997-02-01     0.084

In [ ]:
index_div_yield = db.raw_sql("""
                                select  b.issue_type, 
                                        b.index_flag, 
                                        b.exchange_d, 
                                        b.sic, 
                                        b.secid, 
                                        b.ticker, 
                                        b.cusip, 
                                        a.date, 
                                        a.rate  
                                from optionm_all.idxdvd a, optionm_all.securd b
                                where a.secid = b.secid
                                and b.ticker = 'SPX'
                                and a.date >= '01/01/2020'
                                and a.date <= '12/31/2021'
                                order by a.date
                             """, 
                             date_cols=['a.date'])
index_div_yield.shape

Loading library list...
Done

(505, 9)

In [ ]:
index_div_yield

,issue_type,index_flag,exchange_d,sic,secid,ticker,cusip,date,rate
0,A,1,32768.0,9999,108105.0,SPX,64881510,2020-01-02,1.777138
1,A,1,32768.0,9999,108105.0,SPX,64881510,2020-01-03,1.783770
2,A,1,32768.0,9999,108105.0,SPX,64881510,2020-01-06,1.804811
3,A,1,32768.0,9999,108105.0,SPX,64881510,2020-01-07,1.809661
4,A,1,32768.0,9999,108105.0,SPX,64881510,2020-01-08,1.797900
...,...,...,...,...,...,...,...,...,...
500,A,1,32768.0,9999,108105.0,SPX,64881510,2021-12-27,1.245086
501,A,1,32768.0,9999,108105.0,SPX,64881510,2021-12-28,1.248356
502,A,1,32768.0,9999,108105.0,SPX,64881510,2021-12-29,1.252619
503,A,1,32768.0,9999,108105.0,SPX,64881510,2021-12-30,1.246516
504,A,1,32768.0,9999,108105.0,SPX,64881510,2021-12-31,1.243227